# SQLite version 3.x
# LDAP BIND UID and passphrase file

development:
  username: uid=eecs_vdms,ou=applications,dc=berkeley,dc=edu
  password: 

test:
  username: uid=eecs_vdms,ou=applications,dc=berkeley,dc=edu
  password: 

production:
  username: uid=eecs_vdms,ou=applications,dc=berkeley,dc=edu
  password: 
