# This file stores app-wide settings that must be specified before deployment
# and remain unchanged thereafter
#
# All lengths of time are in seconds.
divisions:
  - Computer Science
  - Electrical Engineering
areas:
  - Artificial Intelligence
  - Biosystems & Computational Biology
  - Communications & Networking
  - Computer Architecture & Engineering
  - Control, Intelligent Systems, and Robotics
  - Database Management Systems
  - Design of Electronic Systems
  - Education
  - Energy
  - Graphics
  - Human-Computer Interaction
  - Integrated Circuits
  - Micro/Nano Electro Mechanical Systems
  - Operating Systems & Networking
  - Physical Electronics
  - Programming Systems
  - Scientific Computing
  - Security
  - Signal Processing
  - Theory
meeting_length: 900
meeting_gap: 300

