# This file stores app-wide settings that must be specified before deployment
# and remain unchanged thereafter
divisions:
  cs: Computer Science
  ee: Electrical Engineering
areas:
  ai: Artificial Intelligence
  bio: Biosystems & Computational Biology
  comnet: Communications & Networking
  arc: Computer Architecture & Engineering
  cir: Control, Intelligent Systems, and Robotics
  dbms: Database Management Systems
  des: Design of Electronic Systems
  educ: Education
  ene: Energy
  gr: Graphics
  hci: Human-Computer Interaction
  inc: Integrated Circuits
  mems: Micro/Nano Electro Mechanical Systems
  osnt: Operating Systems & Networking
  phy: Physical Electronics
  ps: Programming Systems
  sci: Scientific Computing
  sec: Security
  sp: Signal Processing
  thy: Theory
