# This file stores app-wide settings that must be specified before deployment
# and remain unchanged thereafter
#
# All lengths of time are in seconds.
divisions:
  cs: Computer Science
  ee: Electrical Engineering
areas:
  ai: Artificial Intelligence
  bio: Biosystems & Computational Biology
  comnet: Communications & Networking
  arc: Computer Architecture & Engineering
  cir: Control, Intelligent Systems, and Robotics
  dbms: Database Management Systems
  des: Design of Electronic Systems
  educ: Education
  ene: Energy
  gr: Graphics
  hci: Human-Computer Interaction
  inc: Integrated Circuits
  mems: Micro/Nano Electro Mechanical Systems
  osnt: Operating Systems & Networking
  phy: Physical Electronics
  ps: Programming Systems
  sci: Scientific Computing
  sec: Security
  sp: Signal Processing
  thy: Theory
meeting_length: 1200
meeting_gap: 0
scheduler_scores:
  is_meeting_possible_score: 50000
  is_meeting_possible_penalty: -50000
  faculty_ranking_weight_score: 739
  faculty_ranking_default: 0
  admit_ranking_weight_score: 523
  admit_ranking_default: 0
  area_match_score: 1532
  area_match_default: 0
  one_on_one_score: 50000
  one_on_one_penalty: 0
  one_on_one_default: 0
  mandatory_score: 50000
  mandatory_default: 0
  consecutive_timeslots_default: 0
  consecutive_timeslots_weight_score: 10000
  number_of_spots_per_admit: 1
  chromosomal_inversion_probability: 0.5
  point_mutation_probability: 0.3
  double_crossover_probability: 0.2